# -*- coding: utf-8 -*-
"""StartUpFunding2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zS6KOHTzMRx0Ip6LKiAQ1mOTRgq-FyLH
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

df = pd.read_csv("startup_funding.csv")
df=df[['Industry Vertical',
       'City  Location',
       'InvestmentnType',
       'Amount in USD']]
df.dropna(inplace=True)

df['Amount in USD'] = df['Amount in USD'].astype(str)
df['Amount in USD'] = df['Amount in USD'].str.replace(',', '')

df['Amount in USD'] = pd.to_numeric(df['Amount in USD'], errors='coerce')

df.dropna(subset=['Amount in USD'],inplace=True)

industry1=LabelEncoder()
city1=LabelEncoder()
investment1=LabelEncoder()

df['Industry Vertical']=industry1.fit_transform(
    df['Industry Vertical']
)
df['City  Location']=city1.fit_transform(
    df['City  Location']
)
df['InvestmentnType']=investment1.fit_transform(
    df['InvestmentnType']
)
X=df[['Industry Vertical',
      'City  Location',
      'InvestmentnType']]
Y=df['Amount in USD']
X_train,X_test,Y_train,Y_test=train_test_split(
 X,
 Y,
 test_size=0.2,
 random_state=42
)
model=RandomForestRegressor(
    n_estimators=100,
    random_state=42
)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

print("R2_score",r2_score(Y_test,Y_pred))



print("\nAvailable industry")
print(industry1.classes_)

print("\nAvailable city")
print(city1.classes_)

print("\nAvailable InvestmentnType")
print(investment1.classes_)

industry=input("\nEnter industry:")
city=input("enter city:")
investment=input("enter investment Type:")

industry_value=industry1.transform([industry])[0]
city_value=city1.transform([city])[0]
investment_value=investment1.transform([investment])[0]

predict=model.predict(
    [[industry_value,
      city_value,
      investment_value]]
)
print("predict friendly amount(USD)")
print(round(predict[0],2))